name: ClockedOut
options:
  bundleIdPrefix: com.clockedout
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: 6.0.0

targets:
  ClockedOut:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: ClockedOut
    resources:
      - path: ClockedOut/Assets.xcassets
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.clockedout.ClockedOut
      PRODUCT_NAME: ClockedOut
      MACOSX_DEPLOYMENT_TARGET: "13.0"
      SWIFT_VERSION: "5.9"
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: GRDB
        product: GRDB
    info:
      path: ClockedOut/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "13.0"
        NSHumanReadableCopyright: ""
        NSPrincipalClass: NSApplication
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false

